# Generated by Django 5.2.12 on 2026-04-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="attendance",
            table="Attendance",
        ),
        migrations.AlterModelTable(
            name="embedding",
            table="Embeddings",
        ),
        migrations.AlterModelTable(
            name="employee",
            table="Employees",
        ),
    ]
