# Generated by Django 5.2.12 on 2026-04-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_customuser_loginlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
